### ISSUE TITLE
npm auth token yarn error

### ISSUE THREAD

**Issue by KonradHoeffner** [Onto-Med/top-frontend#340]
I have exported my GitHub classic token to the NPM_AUTH_TOKEN environment variable but I get the following error with yarn:

```
frontend$ yarn
yarn install v1.22.21
error Error: Failed to replace env in config: ${NPM_AUTH_TOKEN}
    at /usr/lib/node_modules/yarn/lib/util/env-replace.js:19:13
    at String.replace (<anonymous>)
    at envReplace (/usr/lib/node_modules/yarn/lib/util/env-replace.js:14:16)
    at NpmRegistry.normalizeConfig (/usr/lib/node_modules/yarn/lib/registries/npm-registry.js:423:69)
    at /usr/lib/node_modules/yarn/lib/registries/npm-registry.js:455:36
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by KonradHoeffner** [comment]
Does yarn ignore .npmrc?

**Comment by ChristophB** [comment]
Both `.yarnrc` and `.npmrc` are working for me. Is your env var set correctly?
BTW: There is a devcontainer setup in the `.devcontainer` folder to improve reproducibility.

**Comment by KonradHoeffner** [comment]
Only occurs on my machine, seems to be user error.
